name: CI Pipeline

on:
  push:
    branches:
      - main  
# Declaro la rama en la se hará el build 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21'  # Cambia esto a la versión de Node.js que necesites

      - name: Install dependencies
        run: npm install

      - name: Build the application
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: react-build
          path: build/  # Cambia esto si tu carpeta de build tiene otro nombre